stages:
  - build

build-and-push:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  only:
    - deploy
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t cristian102711/front-despacho:latest .
    - docker push cristian102711/front-despacho:latest